'data.world-r
Copyright 2017 data.world, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

This product includes software developed at data.world, Inc.(http://www.data.world/).'

#' An adapter class to data package structure generated by https://github.com/frictionlessdata/datapackage-r
#' @param structure - a structure object returned `datapkg::datapkg_read`
#' @param dataset the  "agentid/datasetid" for the dataset from
#' which to download the datapackage
#' @examples
#' \dontrun{
#' cities <- datapkg_read("git://github.com/datasets/world-cities")
#' package <- data.world::dataPackage(cities)
#' }
#' @export
DataPackage <- function(structure, dataset) {
  me <- list (
    rawStructure = structure,
    dataset = dataset,
    name = structure$name,
    url = structure$homepage
  )
  class(me) <- "DataPackage"
  me
}

#' List all the tables in a datapackage
#' @param dataPackage a datapackage
#'
#' @export
listTables <- function(dataPackage) {
  UseMethod("listTables")
}

#' @export
listTables.default <- function(dataPackage) {
  stop("nope.")
}

#' @export
listTables.DataPackage <- function(dataPackage) {
  resources <- dataPackage$rawStructure$resources
  return(resources[resources$format == "csv", ][["name"]] )
}

#' Load table into a data frame
#' @param datapackage a datapackage
#' @param table a valid table name
#'
#' @export
loadTable <- function(datapackage, table) {
  UseMethod("loadTable")
}

#' @export
loadTable.default <- function(datapackage, table) {
  stop("nope.")
}

#' @export
loadTable.DataPackage <- function(datapackage, table) {
  table <- validateTableName(datapackage, table)
  return(datapackage$rawStructure$data[[table]])
}

#' return a schema structure of the table
#' @param datapackage a data package
#' @param table a valid table name
#'
#' @export
loadSchema <- function(datapackage, table) {
  UseMethod("loadSchema")
}

#' @export
loadSchema.default <- function(datapackage, table) {
  stop("nope.")
}

#' @export
loadSchema.DataPackage <- function(datapackage, table) {
  table <- validateTableName(datapackage, table)
  resources <- datapackage$rawStructure$resources
  schema <- resources[resources$name==table,]$schema$fields[[1]]
  schema[["rtype"]] <- unlist(lapply(schema$type , function (x) {as.character(data.world::datatypes(datapackage = x)$r)}))
  return(schema)
}

validateTableName <- function(datapackage, table) {
  tables <- data.world::listTables(datapackage)
  if (table %in% tables) {
    return(table)
  } else {
    stop(sprintf("table %s is not found. Available tables are : %s", table, paste(tables, collapse = ", ")))
  }
}

