'data.world-r
Copyright 2017 data.world, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.

You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.

This product includes software developed at data.world, Inc.(http://www.data.world/).'

#' An adapter class to data package structure generated by https://github.com/frictionlessdata/datapackage-r
#' @param dataset the  "agentid/datasetid" for the dataset from
#' which to download the datapackage
#' @param datapackagePath path to where datapackage.json is
#'
#' @export
LocalDataset <- function(dataset, datapackagePath) {
  structure <- datapkg::datapkg_read(datapackagePath)
  # load dataset

  me <- list (
    rawStructure = structure,
    dataset = dataset,
    name = structure$name,
    url = structure$homepage,
    localCachepath = datapackagePath,
    tables = structure$data,
    schema = loadSchema(structure)
  )
  class(me) <- "LocalDataset"
  me
}

#' @export
summary.LocalDataset <- function(localDataset, ... ) {
  summary <- list()
  for (tableName in names(localDataset$tables)) {
    summary[[tableName]] <- summary(localDataset$tables[[tableName]])
  }
  return(summary)
}

#' @export
print.LocalDataset <- function(localDataset, ...) {
  tables <- list()
  for (tableName in names(localDataset$tables)) (
    tables[[tableName]] = names(localDataset$tables[[tableName]])
  )
  return(print(list(dataset = localDataset$url, name = localDataset$dataset , tables = tables)))
}

loadSchema <- function(rawStructure) {
  schema <- list()
  resources <- rawStructure$resources
  for (tableName in  resources[['name']]) {
    schema[[tableName]] <- resources[resources$name==tableName,]$schema$fields[[1]]
  }
  return(schema)
}

#' @export
describe <- function(object, ...) {
  UseMethod("describe")
}

#' @export
describe.LocalDataset <- function(localDataset, tableName = NULL) {
  if (is.null(tableName)) {
    return(localDataset$schema)
  } else {
    return(localDataset$schema[[tableName]])
  }
}

generateTimestamp <- function () {
  return(as.integer(as.POSIXct(Sys.time(), "UTC")))
}
